# Constants for the application
Net_Wealth = "riquezanet"
PEOPLE_IN_HOUSEHOLD = "np1"
Income = "renthog21_eur22"
wealth_percentile = "percriq"
working_status = "nsitlabdom"
income_percentile = "percrent"
Num_Workers = "nnumadtrab"
Primary_Residence = "p2_70"
Business_Value = "valhog"
Residence_Ownership = "np2_1"
Business_Ownership = "havenegval"